# Generated by Django 4.0.6 on 2022-07-26 17:20

import django.db.models.deletion
from django.db import migrations, models

import url.models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('referer', models.URLField(blank=True)),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('key', models.CharField(default=url.models.generate_key, max_length=3, primary_key=True, serialize=False)),
                ('target', models.URLField(unique=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UrlData',
        ),
        migrations.AddField(
            model_name='hit',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url.shorturl'),
        ),
    ]
