# Generated by Django 4.0.6 on 2022-07-26 17:49

from django.db import migrations, models

import url.models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_hit_shorturl_delete_urldata_hit_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='ttl',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='key',
            field=models.CharField(default=url.models.generate_key, max_length=5, primary_key=True, serialize=False),
        ),
    ]
